name: Build and deploy JAR app to Azure Web App

on:
  push:
    branches:
      - FinalProject
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: ShoppingCartWeb
  JAVA_VERSION: '11'
  DISTRIBUTION: zulu

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: FinalProject

      - name: Set up Java version
        uses: actions/setup-java@v3.0.0
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.DISTRIBUTION }}
          cache: 'maven'

      - name: Build with Maven
        run: mvn clean install

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: java-app
          path: '${{ github.workspace }}/target/*.jar'

  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: java-app

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: |
            {
              "clientId": "5a74f6b1-a40f-409d-9866-9408837bedb6",
              "clientSecret": "LXF8Q~C7KVcoNgXTw0GPD_FUMpxFky8K_ZY~XduQ",
              "tenantId": "59625368-734a-4566-8dc1-0b9cd80ae4b2",
              "objectId": "d4197a4d-927d-4177-9ba6-19d3a4deab56"
            }

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: '*.jar'
